export const data = [
  {
    id: "1",
    img: "img/pcLenovo.png",
    name: "PC 1",
    Marca: "Lenovo",
    Sis: "Windows 10 home premium",
    procesador: "Core i3 4th",
    ram: "4GB",
    DD: "1TB",
    Puertos: "2 USB 3.0, 1 USB 2.0, lector SD",
    tarjetaGrafica: "No",
    Pantalla: "Brillante pantalla de 19'' HD",
    Conectividad: "Bluetooth, Wifi",
    Otros: "",
  },
  {
    id: "2",
    img: "img/pcLenovo.png",
    name: "PC 2",
    Marca: "Lenovo",
    Sis: "Windows 10 home premium",
    procesador: "Core i3 4th",
    ram: "4GB",
    DD: "1TB",
    Puertos: "2 USB 3.0, 1 USB 2.0, lector SD",
    tarjetaGrafica: "No",
    Pantalla: "Brillante pantalla de 19'' HD",
    Conectividad: "Bluetooth, Wifi",
    Otros: "",
  },
  {
    id: "3",
    img: "img/pcLenovo.png",
    name: "PC 3",
    Marca: "Lenovo",
    Sis: "Windows 10 home premium",
    procesador: "Core i3 4th",
    ram: "4GB",
    DD: "1TB",
    Puertos: "2 USB 3.0, 1 USB 2.0, lector SD",
    tarjetaGrafica: "No",
    Pantalla: "Brillante pantalla de 19'' HD",
    Conectividad: "Bluetooth, Wifi",
    Otros: "",
  },
  {
    id: "4",
    img: "img/pcLenovo.png",
    name: "PC 4",
    Marca: "Lenovo",
    Sis: "Windows 10 home premium",
    procesador: "Core i3 4th",
    ram: "4GB",
    DD: "1TB",
    Puertos: "2 USB 3.0, 1 USB 2.0, lector SD",
    tarjetaGrafica: "No",
    Pantalla: "Brillante pantalla de 19'' HD",
    Conectividad: "Bluetooth, Wifi",
    Otros: "",
  },
  {
    id: "5",
    img: "img/pcIntel.png",
    name: "PC 5",
    Marca: "Intel NUC7I7BNH KIT",
    SO: "Windows 10 home premium",
    procesador: "Dual Core i7 7ma",
    ram: "32GB",
    DD: "M2 y SATA 3",
    Puertos: "4 USB 3.0",
    tarjetaGrafica: "Intel Iris Plus Graphics 650",
    Pantalla: "",
    Conectividad: "",
    Otros: "Micro SD",
  },
  {
    id: "6",
    img: "img/pcIntel.png",
    name: "PC 6",
    Marca: "Intel NUC7I7BNH KIT",
    SO: "Windows 10 home premium",
    procesador: "Dual Core i7 7ma",
    ram: "32GB",
    DD: "M2 y SATA 3",
    Puertos: "4 USB 3.0",
    tarjetaGrafica: "Intel Iris Plus Graphics 650",
    Pantalla: "",
    Conectividad: "",
    Otros: "Micro SD",
  },
  {
    id: "7",
    img: "img/pcIntel.png",
    name: "PC 7",
    Marca: "Intel NUC7I7BNH KIT",
    SO: "Windows 10 home premium",
    procesador: "Dual Core i7 7ma",
    ram: "32GB",
    DD: "M2 y SATA 3",
    Puertos: "4 USB 3.0",
    tarjetaGrafica: "Intel Iris Plus Graphics 650",
    Pantalla: "",
    Conectividad: "",
    Otros: "Micro SD",
  },
  {
    id: "8",
    img: "img/pcIntel.png",
    name: "PC 8",
    Marca: "Intel NUC7I7BNH KIT",
    SO: "Windows 10 home premium",
    procesador: "Dual Core i7 7ma",
    ram: "32GB",
    DD: "M2 y SATA 3",
    Puertos: "4 USB 3.0",
    tarjetaGrafica: "Intel Iris Plus Graphics 650",
    Pantalla: "",
    Conectividad: "",
    Otros: "Micro SD",
  }
];