export const data = [
  {
    id: "1",
    img: "img/pc.png",
    name: "PC 1",
    procesador: "Core i3",
    ram: "4GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "2",
    img: "img/pc.png",
    name: "PC 2",
    procesador: "Core i5",
    ram: "2GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "3",
    img: "img/pc.png",
    name: "PC 3",
    procesador: "Core i3",
    ram: "4GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "4",
    img: "img/pc.png",
    name: "PC 4",
    procesador: "Core i5",
    ram: "4GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "5",
    img: "img/pc.png",
    name: "PC 5",
    procesador: "Core i3",
    ram: "2GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "6",
    img: "img/pc.png",
    name: "PC 6",
    procesador: "Core i7",
    ram: "4GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "7",
    img: "img/pc.png",
    name: "PC 7",
    procesador: "Core i3",
    ram: "4GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "8",
    img: "img/pc.png",
    name: "PC 8",
    procesador: "Core i7",
    ram: "2GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "9",
    img: "img/pc.png",
    name: "PC 9",
    procesador: "Core i3",
    ram: "2GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
  {
    id: "10",
    img: "img/pc.png",
    name: "PC 10",
    procesador: "Core i5",
    ram: "4GB",
    tarjetaMadre: "H410M S2H",
    tarjetaGrafica: "No",
    ultimoMantenimiento: "10/12/2020",
  },
];